### ISSUE TITLE
Conda version of signature.tools.lib available

### ISSUE THREAD

**Issue by pdiakumis** [Nik-Zainal-Group/signature.tools.lib#22]
Hi, just thought of letting you know that I've released a conda version of your R package at <https://anaconda.org/pdiakumis/r-signature.tools.lib> (together with [NNLM](https://github.com/linxihui/NNLM) which isn't available from CRAN), in case it helps others.
If you haven't heard of conda, it allows you to easily install R/Python/Bioinformatics tools in a HPC environment (more info at https://docs.conda.io/en/latest/).
I based the conda package off my fork of signature.tools.lib (https://github.com/pdiakumis/signature.tools.lib), which differs from this repo by a single commit (https://github.com/pdiakumis/signature.tools.lib/commit/d8258bab66a2b9d621d68d4f8f123ecfe8182d03).
Note that these conda releases are only for Linux systems (i.e. not Mac/Windows).

Hope that's okay and let me know if there are any issues.

**Comment by andreadega** [comment]
Hi Peter,

Thanks for your work! It is nice to see that more people are using our tools and your conda version will certainly make life easier to others.

In general, we use github for public release and update this repository only for major upgrades or hotfixes. We do what we can to provide a comprehensive package, though our focus is mostly on research, so it is nice when others like you provide additional help. Installation/deployment help like in this case, is very welcome.

It is more complicated when someone comes with an extension to our package in terms of functionalities. We may just not be able to add that, because our dev version may already have it, or it is planned to be done in a different way.
