### ISSUE TITLE
Does SignatureExtraction() function support automatically selection of number of mutational signatures

### ISSUE THREAD

**Issue by WuyangFF95** [Nik-Zainal-Group/signature.tools.lib#23]
Dear @andreadega ,

I really like the package signature.tools.lib because it provides the powerful function SignatureExtraction() to extract mutational signatures. My question is I had a hard time in selecting number of mutational signatures, when I input a WGS catalog matrix and select **nsig = 2:10** and obtained a diagnostic plot like this:

![Sigs_OverallMetrics_test_nboots2_MC](https://user-images.githubusercontent.com/32476254/97143985-a24a9300-179e-11eb-8f80-009788a834bf.jpg)

In my study, I need to run the computational approach on 20 different catalog datasets, and it would be a pain if **signature.tools.lib** does not support automatically selection of **nsig** as **NMF::nmfEstimateRank()** does. Can you tell me whether and how does **signature.tools.lib** selects number of mutational signatures automatically? Thanks!

**Comment by WuyangFF95** [comment]
I have a few more questions:

1. In previous issue (#4 ), you suggested users to use matched clustering (**MC**) rather than hierarchical clustering or partitioning around the medoids. Does this suggestion applicable to all types of tumors, or there are some exceptions?
 
2. There are 3 **nmfmethod**s (brunet, lee, nsNMF). Do you have a preference over any one of these? 

3. I've seen that in previous issues (#4 #17 ), you suggested users to specify **nboots = 20** and **nrepeats = 200**. It would take too long for me if I run with these parameters on 20 datasets each with 500 tumors. Is it necessary to run 20 bootstraps with 200 repeats? Or is it also good if I go with default parameters (**nboots = 2**, **nrepeats = 10**)?

**Comment by andreadega** [comment]
Thanks for the appreciation and feedback!

Unfortunately we do not have a function that returns the number of signatures automatically. You can see Alexandrov et al. 2013 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3588146/) for more information on how to choose. In general, you would like the signatures to be different (so high ave.SilWid in the plot above), and the error between the model and the orginal catalogue to be low. In your case it seems that the number 2 is optimal. At the same time, there are other factors that come with experience in practice. For example, depending on the tumour type, you might have prominent signatures that dominate your data, such as UV light signatures in Skin cancer, or Signature 17 in Esophagus, which might create problems, such as having the first 2 or 3 signatures as just an overslipt of the same signature. I cannot know if this is your case, without more information.

I admit that it would be nice to have an automated method to return the optimal number of signatures, so we will see if we can provide one in future releases.

To answer your other questions:

1. MC is the only clustering method we provide that uses constrained clustering for signature extraction results. As we showed in our recent paper (Nature Cancer 2020), constrained clustering works best, so I would advice to use it in all cases.
2. The three NMF methods correspond to the three methods we analysed in our recent paper. Brunet corresponds to Lee and Seung multiplicative algorithm with KLD objective function, which was the best performing algorithm, so we advise to use it.
3. According to our analysis in our recent paper, 20 bootstrap and 200 repeats works well. You can try to lower it a little, but for 500 WGS samples, I would not go lower than that. I know it is very computationally expensive, we run this on a computer cluster, using 20 cpu on one node, so that each of the 20 bootstraps can run on a single cpu. The reason why we need to run 200 repeats, is because our algorithm then selects the best performing runs, which we showed resulting in the most accurate results. If you only use 10 repeats and 2 bootstraps, your results may not be very reliable or reproducible.

I hope this helped, feel free to contact me if you need more help/information.

**Comment by WuyangFF95** [comment]
Dear @andreadega 

Thanks for your answer! This reply really addresses my doubts and questions.
