### ISSUE TITLE
Understanding the samples x signature exposures table

### ISSUE THREAD

**Issue by annahoge** [Nik-Zainal-Group/signature.tools.lib#25]
Hello and thank you for your tool!

I am running rearrangement signature fit.  My goal is to compare the extent of signature exposure between samples for each signature.  I see three representations of signature exposure per sample, and I'm having trouble understanding how the numbers in each representation relate to each other, or how to compare these numbers across samples.

For signature fit, here is an example of the output for one sample in SigFit_withBootstrap_Exposures_mKLD_bfmCosSim_alpha-1_tr5_p0.05.tsv:

![Screen Shot 2020-12-14 at 9 49 39 AM](https://user-images.githubusercontent.com/36393555/102116350-b0f21580-3df1-11eb-9886-c0bd29adb201.png)

The same sample in SigFit_withBootstrap_Exposures_mKLD_bfmCosSim_alpha-1_tr5_p0.05.jpg:

![Screen Shot 2020-12-14 at 9 49 17 AM](https://user-images.githubusercontent.com/36393555/102116310-a2a3f980-3df1-11eb-81c8-2df51bba6559.png)

And the same sample in sigfit_bootstrap_1ofX.jpg:

![Screen Shot 2020-12-14 at 9 50 16 AM](https://user-images.githubusercontent.com/36393555/102116410-c6ffd600-3df1-11eb-87f4-ad75e7235e9a.png)

For this sample, there are 309 rearrangements in the catalogue and 236 rearrangements in the model.

Why are the numbers in SigFit_withBootstrap_Exposures_mKLD_bfmCosSim_alpha-1_tr5_p0.05.tsv and .jpg different?  How do you recommend comparing signature exposures between samples?  For example, would it be appropriate to normalize the numbers in SigFit_withBootstrap_Exposures_mKLD_bfmCosSim_alpha-1_tr5_p0.05.tsv to be fractions that add up to 1 for each sample?  For this to be appropriate, would I need to set threshold_percent to 0 in SignatureFit_withBootstrap_Analysis, and in that case, is threshold_p.value used?

Thank you so much for your help!

**Comment by andreadega** [comment]
Hi Anna,

Thanks for using our package. And sorry for the lack of explanation of some of these details. We tried to explain everything in the paper, but then the limited space makes the details a bit hard to find.

So, your questions:

1. Why are the numbers in SigFit_withBootstrap_Exposures_mKLD_bfmCosSim_alpha-1_tr5_p0.05.tsv and .jpg different?

The tsv contains the count of mutations and the jpg contains the same info but as a % w.r.t. the total rearrangements (309), so for example: 44.21/309*100=14.31.

2. How do you recommend comparing signature exposures between samples? For example, would it be appropriate to normalize the numbers in SigFit_withBootstrap_Exposures_mKLD_bfmCosSim_alpha-1_tr5_p0.05.tsv to be fractions that add up to 1 for each sample? For this to be appropriate, would I need to set threshold_percent to 0 in SignatureFit_withBootstrap_Analysis, and in that case, is threshold_p.value used?

Different comparisons have different meaning. You may want to know which samples are dominated by a certain signature, so a relative unit, such as normalising the sum to 1 or to 100 could be used. We tend to find the actual count of rearrangements more useful. Also results of fit in samples with a large number of mutations tend to be more reliable.

We use thresholds to reduce the number of false positives, and this can be tailored for each sample if you like. It is always a trade off: lower threshold mean more false positives and less false negatives.

In our Nature Cancer 2020 paper we use this bootstrap approach and leave out the mutations that are removed by the threshold, and this is why there are only 236 mutations in the results. We do this because the difference (309-236) tells us about the uncertainty of signature fit. We showed that this uncertainty is reduced when one fits using less signatures.

Do you have different things to play with if you want to improve the fit. Either you lower the threshold and/or change p-value, or remove some signatures from the fit set, which you may have reasons to believe they are not there. To decide whether a signature is there or not, you can run different fits with different signature sets, and check whether removing a certain signature makes a difference or not (for example, if it increases the error/reduces cosine similarity with the orginal catalogue)

I hope you find this useful,
Andrea

**Comment by annahoge** [comment]
Thank you so much, Andrea!  I really appreciate your thoughtful response.  Happy holidays.
