### ISSUE TITLE
Standardization in applyHRDetectDavies2017

### ISSUE THREAD

**Issue by willhooper** [Nik-Zainal-Group/signature.tools.lib#3]
Hi, in R/HRDetect.R, the function applyHRDetectDavies2017 seems to have mean/sd values hardcoded for each input feature. This results in input data not being standardized to mean=0/sd=1. Is this intentional?

I'm assuming these values come from the results for the 371 samples in the 2017 paper? 

Thanks,
Will

**Comment by andreadega** [comment]
Yes it is intentional. In order for the parameters of the linear model to be meaningful the new input data has to be processed in the same way as the training data, which means that the same mean and sd of the training data should be provided. Please check the R documentation of the function for the details of how to input your data. And thanks for using the package!

**Comment by willhooper** [comment]
Thanks for the fast reply! 

> In order for the parameters of the linear model to be meaningful the new input data has to be processed in the same way as the training data

Would you say that this statement applies to steps upstream of HRDetect? We have a set of samples from non-BRCA cancers, sequenced on a Novaseq, and aligned/called through our in-house pipeline. Are these differences in sequencing/processing are large enough to render the parameters of the model meaningless?

**Comment by andreadega** [comment]
Sorry for closing the issue, your question is quite important and worth a longer reply. 

Before running HRDetect we make sure that the data is of a good quality and try to reduce artefacts and other false positives. We mostly worked with Sanger cgp pipeline, and also adapted output from other pipelines sometimes with filters to get the same level of specificity, and found that HRDetect is quite robust.

What I mean is that rather than retraining HRDetect for different pipelines, we usually prefer to work on the pipeline until we are happy with the calls.

I can advise to have a look at samples in the same tumour type from highly curated resources like PCAWG. You can browse some at signal.mutationalsignatures.com.

**Comment by willhooper** [comment]
Do you think updating the `signature_type` parameter in the HRDetect pipeline function from `COSMIC` to my cancer of interest will give more accurate results? Or when you apply HRDetect to new tumor types, do you stick with COSMIC signatures?

**Comment by andreadega** [comment]
In general yes, though for now in practice it depends on tumour types.

We performed signature extraction in each organ to get the organ specific signatures, which you can also find here https://signal.mutationalsignatures.com/. Some of the tumour types have more reliable signatures than others (e.g. due to sample size, number of signatures present, similarity between signatures present...). Just double check on signal that you are happy with the signatures (both subs and rearr) of your cancer type. We plan to update these signatures as we get more samples, hopefully making them more reliable with the time.

If you choose to use the COSMIC signatures, that can also be fine, though we do not advise fitting all 30 (or soon 60 with the new PCAWG paper) subs signatures at the same time. It is better to try to find which COSMIC signatures to expect in your tumour type. A disadvantage of using the COSMIC option in the signature_type, is that there is no equivalent of COSMIC for rearrangement signatures, so only the rearrangement signatures from the 560 breast cancer paper are used.

In general, a more advanced way to do this, whichever signatures you choose to fit, would be to check whether your fitted model looks like the data (for example using the SignatureFit_withBootstrap_Analysis(...) function, which generates a detailed plot for each sample). The difference between model and data can give you a clue of other signatures that should be added in the fitting (if any). Also, if you are unsure whether a signature is really there or not, then you can try to refit without that signature and see if the similarity between model and data is reduced significantly and whether a pattern similar to the removed signature appears in the difference plot.

I hope this was helpful.

**Comment by willhooper** [comment]
Thanks for your help, Andrea. I'll take a closer look at the signature fitting portion of the pipeline.
