### ISSUE TITLE
SignatureFit_withBootstrap advice

### ISSUE THREAD

**Issue by ahwanpandey** [Nik-Zainal-Group/signature.tools.lib#30]
Hello @andreadega ,

Thanks for all your input regarding the tool!

I understand that you recommend running `SignatureExtraction` first on the data and then running `SignatureFit_withBootstrap` using the extracted signatures. In essence this is just fitting for the signatures that are expected in the data.

As you have mentioned in my issues with windows, I am not able to parallelize `SignatureExtraction` yet:
https://github.com/Nik-Zainal-Group/signature.tools.lib/issues/29

So I thought I'd do the analysis with a different approach. My data is about 10 High Grade Ovarian patients with about 5-6 sites per patient. So there are about 56 WGS VCFs in total. I am trying here to fit with the 60 COSMIC SBS signatures and my workflow is as follows:

1) Do a first fit (FIT_1) using `SignatureFit_withBootstrap` with all 60 signatures and get the mean across all signatures.
2) Check the means and set a cutoff that makes sense and run `SignatureFit_withBootstrap` for a second fit (FIT_2). In the table below, the column "MEAN_FIT_1" is the mean of the first fit across all samples per signature. I've used a cutoff of 200 and re-ran with the top 7 signatures. "MEAN_FIT_2" is the mean after the 2nd fit (note how the enrichment of SBS3 is now much less than FIT_1, with SBS5 being the dominant signature in the cohort).

![image](https://user-images.githubusercontent.com/8450532/131751609-d8f3962a-799c-434d-b957-1ef1020b9b2c.png)

The plot below shows the absolute and relative enrichments for the the first and second fits. The first two plots are for FIT_1 and the 3rd and 4th plots are for FIT_2. The plots have been sorted by patient so they are close to each other for comparison sake. Had to remove the IDs for now.

![image](https://user-images.githubusercontent.com/8450532/131752061-4e1c28e0-08c1-47ac-84d3-f4c852acce1a.png)

The settings I've used for both fits is as follows (just the `reference_signature_mat` changes)
```
SignatureFit_withBootstrap(
    cat = category_counts_mat,
    signature_data_matrix = reference_signature_mat,
    method = "KLD",
    nboot = 100,
    nparallel = 4,
    randomSeed = 42,
    threshold_percent = 5,
    threshold_p.value = 0.05
)
```

Given if you think the above is a fair analysis on my part, I have a couple of questions.

1) You can see that the undetermined is very low in FIT_2. does this really mean that most of the mutations have been successfully and accurately assigned to the 7 signatures? Or, could this also be because now since the playing field (i.e. number of signatures) is quite low, the variation wouldn't be as much as when there were 60 signatures for the bootstrapping to work with.
2) SBS3 is quite prominent across the samples in the first fit which makes sense. But after the second fit, it seems SBS5 has completely taken over. I would presume SBS3 should be enriched to some extent in these samples. So I am not as confident in the results that I am seeing.
3) Since this data is from multiple sites per patient, could the bootstrapping favor the signatures seen in a particular patient with the most number of sites and/or mutations?

Sorry for the long post! I would really appreciate your feedback!

Thanks so much,
Ahwan

**Comment by ahwanpandey** [comment]
I've just done the same analysis with version 2 of the COSMIC SBS signatures with 30 signatures. 

![image](https://user-images.githubusercontent.com/8450532/131761646-f7e5bdb0-c652-4a05-854b-a611935ed626.png)

Signature 5 is now gone and Signature 3 is dominant
Signature 1 is also present now which makes sense given what we have seen in previous studies
But, COSMIC v2 doesn't contain the platinum signatures SBS31 and SBS35 that v3 had.

This was just a quick check to see what it would look like with COSMIC v2. But we do want to do the analysis with v3 that has the platinum signatures.

**Comment by andreadega** [comment]
You seem to have encountered some of the issues we have mentioned in our recent review (_Koh et al. 2021_, Mutational signatures: emerging concepts, caveats and clinical applications).

As you have observed, the signature fit result is very much dependent on the signatures that one uses as input.

Our signature fit with bootstrap approach is designed to give you an idea of how uncertain the fit was. Naturally, the more signatures one uses the more signature combinations are likely to be able to model the data. This is reflected in the large variation in the exposure estimates, and consequently, more mutations left unassigned. In fact, the signatures are unassigned because of how the post-fit filter works: the result is based on the median exposures from the bootstrap fits, but this is set to zero if not enough bootstraps are above a given threshold (95% of boostrap exposures for a signature need to be greater than 5% of total mutations). So naturally, when you reduced the number of signatures to just 7, the accuracy of the fits improved, giving you very little unassigned mutations. Yet this doesn't imply that the fit is good, just that it is a relatively reproducible/robust solution. In machine learning terms you have decreased your variance and increased your bias.

My advice is, you can check which signatures are typically found in ovarian cancer, either look at the COSMIC website, or at our Signal website, and just use those signatures. Then try to see if there are additional signatures you missed. This can be done by comparing the original catalogues and the model (i.e. multiply the signature matrix by the exposures matrix), and perhaps subtracting the model from the catalogue and see what it looks like. Several of these steps can be done using our Analyse section on Signal:

https://signal.mutationalsignatures.com/analyse2

Finally, signature fit works on each sample independently, so it doesn't matter if you have several samples with the same signatures. The use of multiple samples from the same patient can affect instead the signature extraction. If they look very similar and constitute a large part of your data, it may be useful to remove duplicate mutations, so that each mutation is considered only once.

BW,
Andrea

**Comment by andreadega** [comment]
Closed for inactivity.
