### ISSUE TITLE
Rearrangement signature R5 in pancreas

### ISSUE THREAD

**Issue by felixbeaudry** [Nik-Zainal-Group/signature.tools.lib#35]
Hi there!
Thanks for a very cool package! I have a quite specific question: I am running the rearrangement signatures `SignatureFit_withBootstrap_Analysis` for a pancreas sample `getOrganSignatures(organ="Pancreas",typemut = "rearr")` and then converting to reference `convertExposuresFromOrganToRefSigs` and I'm coming across a surprising result: my sample has a lot of Pancreas_C, which in Fig 3 of Degaspari et al 2020 (https://www.nature.com/articles/s43018-020-0027-5) is colored as R5 but in the conversion matrix ([signature.tools.lib](https://github.com/Nik-Zainal-Group/signature.tools.lib)/[data](https://github.com/Nik-Zainal-Group/signature.tools.lib/tree/master/data)/2019_01_10_ConversionMatrix_rearr.tsv ) Pancreas_C is weighted as R9 (weight=1). Since RefSig R5 is associated with BRCAness but not R9, I am getting much less confidence on BRCAness for my pancreas samples when running `HRDetect_pipeline.` May I ask how the conversion matrix was made compared to the manuscript figure?  
Thanks for your help!
Felix

**Comment by andreadega** [comment]
Hi thanks for the compliment!

Sorry about the confusion of Figure 3. The colouring is based on the cosine similarity to the six breast cancer rearrangement signatures that were reported in 2016. The legend of Figure 3 says: "...colored according closest rearrangement signature derived in Nik-Zainal et al.[12], based on cosine similarity.".

In fact, in Pancreas we do not find R5, but only R9, and we consider them somewhat equivalent, because they are both short deletion signatures (see in Figure 6). In fact, for HRDetect we consider both R5 and R9 exposures as the HRDetect input SV5. If you have run HRDetect_pipeline, then the SV5 exposures should include the R9 exposures, and you should be able to see the R9 exposures in the data_matrix returned by the HRDetect_pipeline.

**Comment by andreadega** [comment]
Closed for inactivity.
