### ISSUE TITLE
getting same values for SV3 and SV5 across multiple samples

### ISSUE THREAD

**Issue by anoronh4** [Nik-Zainal-Group/signature.tools.lib#36]
I am attempting to use the HRDetect pipeline for a set of 17 samples (one at a time) and using SV, SNV, and CNV files as inputs. The log says the signatures SV3 and SV5 are being computed: 
```
========= Preprocessing SV inputs =========
mySample
BND DEL DUP INV 
195 120 187  93 
```
But for each sample the SV3 and SV5 come out to `-0.876753168376584` and `-1.10515509103169`, respectively. All samples have between 142 and 1550 SV records in bedpe format -- just wondering if there was any further guidance on input files, and if this seems like a problem to you. we have merged our variant calls together using a tool appropriate for SVs, which creates a vcf file in symbolic notation. Then we convert to Bedpe using [svtools](https://github.com/hall-lab/svtools). Here is an example record used in input:
```
chrom1	start1	end1	chrom2	start2	end2	ID	QUAL	strand1	strand2	svclass	FILTER	NAME_A	REF_A	ALT_A	NAME_B	REF_B	ALT_B	INFO_A	INFO_B	FORMAT	mySample_tumor	mySample_normal	sample
1	963990	963991	1	964388	964389	mypipe_DEL_1_963990	.	+	-	DEL	PASS	mypipe_DEL_1_963990	N	N[1:964388[	.	.	.	delly_CIEND=-55,55;delly_CIPOS=-55,55;delly_PE=3;delly_MAPQ=46;delly_CT=3to5;delly_IMPRECISE;delly_SVMETHOD=EMBL.DELLYv0.8.2;delly_RDRATIO=0.266474;delly_SOMATIC;Callers=delly;NumCallers=1;CHR2=1;END=964388;SVTYPE=DEL;POS=963990;SVLEN=398;STRANDS=+-;NumCallersPass=1	.	GT:delly_GQ:delly_FT:delly_RC:delly_RCL:delly_RCR:delly_CN:delly_DR:delly_DV:delly_RR:delly_RV	./.:10000:PASS:4764:21384:17232:0:18:7:0:0	./.:53:PASS:8026:8598:8738:1:18:0:0:0	mySample
```

**Comment by andreadega** [comment]
Hi there,

Hopefully I can help you, some questions for you:

- How did you run the pipeline? did you use the hrDetect command line script or the ```HRDetect_pipeline()``` R function?
- Can you give me the list of parameters you used to run it? Did you specify an organ to run organ-specific signaturers or did you use COSMIC signatures?

Now, I would advise you to make sure you have read the documentation by typing ```?HRDetect_pipeline``` in R. In your case, the most important part to read would be the description of the parameter ```SV_bedpe_files```. This description explains how the bedpe files should be constructed. Looking at your example above, you seem to have specified the required ```svclass``` column, though the content seems to be incorrect, as it says "DEL" instead of "deletion". The values in the ```svclass``` column should be: translocation, inversion, deletion, tandem-duplication. Hopefully, this will fix the classification, which in turn should lead to correct SV catalogues and signature assignment.

The values of SV3 and SV5 you report are those from the hrdetect output table and are obtained by standardising the input and multiplying it for the corresponding linear model weight. These numbers come up if the number of mutations assigned to SV3 and SV5 is 0, so it makes sense that if you didn't classify the rearrangements correctly, then you got 0 SV3 and 0 SV5 in all your samples.

**Comment by anoronh4** [comment]
Hi, we used the function with the following parameters:
```
HRDetect_pipeline(input_matrix,
                      genome.v = genome_version,
                      SV_bedpe_files = SV_bedpe_files,
                      Indels_tab_files  = Indels_tab_files,
                      CNV_tab_files = CNV_tab_files,
                      SNV_catalogues = SNV_catalogues,
                      nparallel = n_parallel)
```
Looks like we are using the default for `signature_type`. Making the adjustment to the svclass column certainly seems to make a difference. The values for SV3 and SV5 are no longer uniform and the Probability values look promising. 

I will take a better look at the manual. Thanks!
