### ISSUE TITLE
Non-cancer (healthy) tissues

### ISSUE THREAD

**Issue by gevro** [Nik-Zainal-Group/signature.tools.lib#40]
Hi,
For FitMS, what should we set organ to for non-cancer (healthy) tissues? It seems that the organ is generally applying signatures found in cancers of each organ, but we don't necessarily know if those signatures are prevalent in healthy tissues of that organ. Therefore, is there a setting you recommend for non-cancer (healthy) tissues?

Thanks

**Comment by andreadega** [comment]
Personally, what I would try to do is to start from signatures that are known to be present in the healthy tissue you are working with. I think SBS1, SBS5 and perhaps SBS18 might be a good general starting point. I would use fitMS so that these common signatures can be fit first and at the same time you can specify a set of rare signatures to check as a second step, for example SBS7 (UV) or SBS4 (Smoking). If the tissue of origin is skin then perhaps SBS7 might go into the common signatures set. You might have to play around a bit to see what works. If you want to use organ specific signatures, you might want to try a subset of the common cancer signatures for that tissue type, though we don't yet know if healty tissue organ signatures are the same as the cancer organ signatures.

**Comment by gevro** [comment]
Thank you!
