### ISSUE TITLE
eHRDetect 

### ISSUE THREAD

**Issue by ruolin** [Nik-Zainal-Group/signature.tools.lib#49]
I came across a [paper](https://www.annalsofoncology.org/article/S0923-7534(23)00047-9/fulltext) citing eHRDetect. I have used the HRDetect for WGS data before. I want to use eHRDetect for some WES (Exome) data but I couldn't find how HRDtect was modified. I thought there could be some non-trivial steps involved.

**Comment by andreadega** [comment]
You may find some information in the methods section of that paper, though not a lot. We retrained a logistic regression classifier as we did in the original HRDetect paper, but used only the mutational data available in exomes. It is quite tricky to use because of the low number of mutations in exomes, especially indels. If you would like to discuss further, please reach out to me via email.
