### ISSUE TITLE
Confusion in bedpeToRearrCatalogue.Rd

### ISSUE THREAD

**Issue by DarioS** [Nik-Zainal-Group/signature.tools.lib#9]
There is one input parameter with explanation "data frame BEDPE as described above" but there's nothing above the that text except for the function usage and function name. Details has "Sanger BRASS convention" but I don't know anything about it. Perhaps a link would be useful to guide the reader to somewhere with more details about the convention, using the `\url` macro, such as `\url{https://www.sanger.ac.uk/}`. Also, how about providing some example code to assist users to create a BEDPE file themselves? There is already good support in Bioconductor for this task.

```r
library(StructuralVariantAnnotation) # Bioconductor package.
vcf <- readVcf("/path/to/patient.vcf.gz")
gRanges <- breakpointRanges(vcf)
breakpointgr2bedpe(gRanges)
```

Showing this in the README file or a vignette would be nice for novice users.

Also, the example `vcf_sv_file.bedpe <- "sample.bedpe"` and the following importation doesn't work because there doesn't seem to be any `sample.bedpe` file anywhere in the package. It would be helpful if the examples worked the package passed `R CMD check` although there are some more basic problem preventing `R CMD check` even reaching the checking of examples:

```r
$ R CMD check signature.tools.lib/
* checking for file ‘signature.tools.lib/DESCRIPTION’ ... ERROR
Required fields missing or empty:
  ‘Author’ ‘Maintainer’
* DONE

Status: 1 ERROR
```

**Comment by andreadega** [comment]
Thanks for your suggestion. Details on how the bedpe file should be formatted are available by typing ```?bedpeToRearrCatalogue```. I am not sure why it does not appear to you. I can report it here:


Description

This function converts a data frame BEDPE into a rearrangement catalogue, you should pass rearrangements of only one sample, and one rearrangement for each paired-end mates. The BEDPE data fram should contain the following columns: "chrom1", "start1", "end1", "chrom2", "start2", "end2" and "sample" (sample name). In addition, either two columns indicating the strands of the mates, "strand1" (+ or -) and "strand2" (+ or -), or one column indicating the structural variant class, "svclass": translocation, inversion, deletion, tandem-duplication.

Details

The column "svclass" should correspon to (Sanger BRASS convention): (strand1/strand2)

inversion (+/-), if mates on the same chromosome

inversion (-/+), if mates on the same chromosome

deletion (+/+), if mates on the same chromosome

tandem-duplication (-/-), if mates on the same chromosome

translocation, if mates are on different chromosomes

---

We did not include a vcfToBedpe converter because there are different methods, and the one you highlight is only one of them (the other is the svtools python tool). Thanks for providing examples on how to perform the conversion. However, please make sure your output file adheres to the specifications above.

---
I am not sure what ```R CMD CHECK``` does, we may look into it. However, we advise to use devtools to run tests (```devtools::test()```) to check whether our package works properly after installation.

**Comment by DarioS** [comment]
Ah, so it refers to Description and Details sections. The misunderstanding happens because the Usage section explaining each variable is placed above Details and Description in the final rendering after running `?bedpeToRearrCatalogue`. In your Roxygen documentation, the `@param` statements are at the end of the documentation block, so the Usage and Details sections are above. So, the text should be "as described **below**" for `sv_bedpe` to reflect what the user actually sees in the dynamically generated bedpeToRearrCatalogue.Rd file.

Also, I notice test.bedpe doesn't follow the [BEDPE definition of bedtools](https://bedtools.readthedocs.io/en/latest/content/general-usage.html#bedpe-format), the first project to define BEDPE. User-defined columns must come after column 10, but test.bedpe has sample, name and partner before strand1 and strand2. strand1 and strand2 are required to be in the first set of standard columns (column 9 and column 10). Could signal use the original definition of BEDPE format instead of creating yet another bioinformatics file format? BRASS also [follows the original BEDPE format](https://github.com/cancerit/BRASS/wiki/BEDPE).

**Comment by andreadega** [comment]
We did not try to define a new format, we instead rely on column names to identify which columns contain the required input data. Our sample files are not meant to define a standard, they are generated from different algorithms (Manta or Brass annotated output), but they do contain the column identifier that are required in the function desctiption. Sorry if this was confusing.
